### ISSUE TITLE
Compiling grey-cuckoo on Guest VM (OSX 10.13)

### ISSUE THREAD

**Issue by PwnU** [phdphuc/mac-a-mal#1]
Posting this for posteriority from mac-a-mal-cuckoo
Grey-cuckoo builds but no executable is created.
Without it every time I kextload mac-a-mal.kext the VM reboots (kernel crashes) and can't do anything with grey-cuckoo.

**Comment by phdphuc** [comment]
macOS >= 10.13 is not yet supported.
